name: release-to-maven-central
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Release version ${{ github.event.inputs.releaseversion }}!"

      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: oss.sonatype.org
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set projects Maven version to GitHub Action GUI set version
        run: mvn versions:set "-DnewVersion=${{ github.event.inputs.releaseversion }}"

      - name: Publish package
        run: mvn --batch-mode clean deploy -P central-deploy -DskipTests=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        with:
          maven-args: "clean install"
          git-release-bot-name: "bot-rocketbase"
          git-release-bot-email: "bot@rocketbase.io"
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}
